services:
  - type: web
    name: wheretomeet-backend
    env: node
    buildCommand: npm run install:all
    startCommand: npm run start:backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: PORT
        value: 5001 