services:
  - type: web
    name: wheretomeet-backend
    env: node
    buildCommand: cd src/backend && npm install
    startCommand: cd src/backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: PORT
        value: 5001 